### ISSUE TITLE
Glossary.md v. API.md

### ISSUE THREAD

**Issue by taion** [reactjs/react-router#2424]
We have this inconsistent semi-duplication between the two. For example, compare:

- https://github.com/rackt/react-router/blob/v1.0.0-rc3/docs/API.md#onenternextstate-replacestate
- https://github.com/rackt/react-router/blob/v1.0.0-rc3/docs/Glossary.md#enterhook

This is going to be painful and tedious, but it'd be nice if we could reconcile them (and maybe get rid of the function signature listings and descriptions in the glossary).

**Comment by taion** [comment]
Ref #2423 - we were documenting async `onEnter` hooks in the latter but not the former above!

**Comment by mjackson** [comment]
Let's keep them separate. Glossary.md is just terms, definitions. API.md (and all the other docs) should link to Glossary.md frequently to avoid the need to re-explain what terms mean.

**Comment by taion** [comment]
Where do you think documentation on e.g. function signatures for hooks should go?

**Comment by mjackson** [comment]
That stuff belongs in the glossary. Then, when you're talking about routes you can just say something like:

> A route can have [an `onEnter` hook](https://github.com/rackt/react-router/blob/master/docs/Glossary.md#enterhook) that is called when the router enters that route.

**Comment by taion** [comment]
:+1: My main concern is just avoiding inconsistency from having the same thing in two places. Pointing to the glossary from the API docs would accomplish this. I've updated the topic of this issue appropriately.

**Comment by taion** [comment]
On second thought, I think we probably should have e.g. hook signatures in the API docs.

If I'm looking at the API documentation, I'd really prefer to be able to e.g. see the expected signature for hooks without having to refer to a separate reference.

It'd be a bit of extra work, but I think it would make the API documentation more usable if hook signatures were present there. As a user, I'd really prefer for the API docs to be as comprehensive a reference to the API as possible.

**Comment by mjackson** [comment]
>  I think we probably should have e.g. hook signatures in the API docs.

@ryanflorence and I converged on this same idea last night. Glossary.md is a great place for definitions of terms. But API docs are where we should be showing method signatures and a few usage examples.

**Comment by taion** [comment]
@timdorr Why close this? I think this still needs to be resolved regardless – we need both a good set of tutorials/guides and a comprehensive reference for use as, well, a reference.

**Comment by timdorr** [comment]
I thought we had everything separated out appropriately, as to the Glossary vs API issue. If we need a rewrite of the guides and doc structure, that is a separate issue from this one.

**Comment by taion** [comment]
No – per https://github.com/rackt/react-router/issues/2424#issuecomment-161256434, the issue is that they're _too_ split out and half our method signatures are still in the Glossary rather than the API.

**Comment by timdorr** [comment]
Then I think the terminology is getting murky here, so I'm beginning to lose the plot. I see a distinct difference between "method/function signatures" mentioned here and "type signatures" mentioned in the glossary. Which is basically just JS vs Flow/TypeScript. Just to be clear, this is what I mean:

**Function signature**
```js
match({ routes, location, [history], ...options }, cb)
```
**Type signature**
```js
type EnterHook = (nextState: RouterState, replace: RedirectFunction, callback?: Function) => any;
```

Sooooo... I think for an API doc you should have code as it's written, since you're going to be throwing in examples nearby and don't want to force the reader to mentally context switch. For the glossary, the content is more conceptual, so Flow/TypeScript-style typings, which don't actually exist in the code, would seem to make sense there. 

Does that all sound right, or is there any disagreement?

If we're all on the same page, then I'm not sure where we're putting one type of signature in the other type of document. I could be missing something, so specific examples would be helpful.

And irrespective of all of this, we should have an issue open for a documentation rewrite effort. I can't track whatever @ryanflorence's doing based on tweets or issue comments, and I certainly don't want to step on his toes if he's got a lot of awesome content built up already. I'll open that up separately.

**Comment by taion** [comment]
Let's consolidate discussion in https://github.com/reactjs/react-router/issues/2424.
