### ISSUE TITLE
Make `matchRoutes` public

### ISSUE THREAD

**Issue by leidegre** [reactjs/react-router#3113]
I'm using `react-router-redux` and it allows me to get at the `location` information but it does not augment my `location` with all the `renderProps` that the `transitionManager` normally provides so, I have this workaround.

https://github.com/reactjs/react-router-redux/issues/297

It accomplishes exactly what I want, in that it exposes the `params` based on the route config in my `@@router/CHANGE_LOCATION` action. Enhancing the action, if you will.

Though, I have to dig up the `matchRoutes` function like so `import matchRoutes from 'react-router/lib/matchRoutes'` and I wonder why we cannot have an API for this exact purpose.

Maybe there's already one but I think the use case is quite clear, better yet augment the location change that is originating from history with the matched route information.

Note sure what the best course of action is here, happy to take notes.

**Comment by taion** [comment]
This is not a stable API that will be made public. If you need to intercept the route params, do so via the `render` hook.

**Comment by leidegre** [comment]
@taion I'm not trying to intercept what's happening in the component, I'm trying to avoid having to duplicate how the routes are defined and how the `params` are read from the URL. Take a closer look at the react-router-redux issue that I've linked and you'll see what I mean. Is there any plan of supporting such a facility?

**Comment by taion** [comment]
It doesn't work the way you think it does – it's not even synchronous, for one.

**Comment by leidegre** [comment]
@taion that's not an issue. An action doesn't have to be synchronous. I've already made all the parts for this, and it works just fine. It's just the internal dependencies that I'd prefer to not touch.

**Comment by leidegre** [comment]
If anyone finds this a render hook could potentially be used to accomplish this.

It's well hidden (https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md)

~~~
<Router render={props => <RouterContext {...props} />} />
~~~

It should be possible to install a higher-order component around the `RouterContext` this in turn could dispatch a location change action to notify the store about a route change.

**Comment by taion** [comment]
I _told_ you that in https://github.com/reactjs/react-router/issues/3113#issuecomment-187770641.

**Comment by landabaso** [comment]
@leidegre thanks for the tip!

This is the way to go. Anyone can try it:

```
  ReactDOM.render(
          <Router history = {history} routes={routes} render={(props)=>{console.log('props', props); return <RouterContext {...props} />;}}/>
    document.getElementById('main'));
```

This makes it very easy to `dispatch` new actions and enhance the state based on params (not only location) when using react-router + redux.

Thanks!

**Comment by landabaso** [comment]
@taion, @leidegre and others that see this issue in the future.

I'm using the render hook but using the undocumented matchRoutes function could offer some benefits too...

When using the render hook it's not possible to set the Redux state before the rendering occurs.

It's not posible to dispatch actions since React will complain for setting the state during the render operation.

You could dispatch actions onUpdate using the <Router onUpdate> hook, but then this is late since your components are forced to render twice.

Why setting a state based on params? Easy, params are SEO friendly stuff that do not match the internal data representation of the state. The only way to set this parsed params is to dispatch actions in componentWillReceiveProps in the components which is kind-of-ugly and forces re-rendering.

Instead, using the undocumented matchRoutes would let us set a listener on Location change and set the sate accordingly as described in the docs here:

http://redux.js.org/docs/api/Store.html#subscribe

I hate using undocumented docs . In fact, there is at least one npm package in the wild using that. See for example: https://www.npmjs.com/package/react-router-redux-params

I hope this helps someone in the future.
