### ISSUE TITLE
Failed to execute 'replaceState' on 'History'

### ISSUE THREAD

**Issue by craigbeck** [reactjs/react-router#3184]
## Version
react-router 1.0.0

## Dependencies
history 1.13.1

## Error

Chrome:
```
DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http:' cannot be created in a document with origin 'http://localhost:8080' and URL 'http://localhost:8080/select'.
    at Error (native)
    at finishTransition (http://localhost:8080/app.js:38970:27)
    at http://localhost:8080/app.js:35432:14
    at http://localhost:8080/app.js:35408:10
    at done (http://localhost:8080/app.js:35725:15)
    at next (http://localhost:8080/app.js:35734:13)
    at Object.loopAsync (http://localhost:8080/app.js:35738:4)
    at confirmTransitionTo (http://localhost:8080/app.js:35394:18)
    at Object.transitionTo (http://localhost:8080/app.js:35420:6)
    at http://localhost:8080/app.js:36771:24
```

Firefox:
```
Unhandled promise rejection DOMException [SecurityError: "The operation is insecure."
code: 18
nsresult: 0x80530012
location: http://multiline-admin.zipwhip.com/app.js:61]
```

I'm getting an error only when using the browser history (i.e. not hash history) . This is happening in a `then()` of a promise returned from an async action like this:

```
handleLogin(credentials) {
  login(credentials)
    .then(() => {
        this.context.history.replaceState("/select");
    });
}
```

So pretty much a standard redirect after login scenario. All I've found relating to the error above seems to be around a change in the host/origin which is not happening in this case.

- The URL in the address bar is changed (i.e. it does have the path of "/select") but the UI does not update to reflect this.
- Other links in the app work fine
- Other invocations of `histroy.replace()` are working
- I have exposed the `history` object via `window.__history` and `window.__history.replace("/select")` works

Any ideas?

**Comment by ryanflorence** [comment]
you can't do `push` or `replace` with something like `http:...`, only the path, like `push('/somewhere')` not `push('http://whatever/somewhere')

**Comment by craigbeck** [comment]
@ryanflorence that's not what I'm doing. I't just the path "/select"

**Comment by craigbeck** [comment]
It looks like it is because there is a second call happening and passing `"/"` which is getting appended to `basename` of `"/"` resulting in the double-slash path in the history module.

![console output](https://cloud.githubusercontent.com/assets/1620605/13761167/387d624a-e9f4-11e5-89fb-fb94ac87ca30.png)

**Comment by dsernst** [comment]
@craigbeck: Were you able to resolve this? I've started to see it crop up mysteriously, hundreds of times in the last week.

**Comment by craigbeck** [comment]
Looking back at source history it's unclear as to what the fix was exactly, but It look like there was an issue when using a basename for the URLs where it was be prepended twice (ending up with "//" as the path) resulting in the unhelpful error above.

**Comment by MoOx** [comment]
I think this issue should be reopened. I am getting it when using a basename that have a single trailing slash ("/") and all links works ("/all", "/whatever") but not "/", which trigger a url with "//" that create the security exception. basename is configurable in my case, that's why I have it with "/".
Maybe a "simple" fix (from the user point of view), is to handle the case where url is being pushed with "//".

**Comment by taion** [comment]
See also https://github.com/reactjs/react-router/issues/3168, https://github.com/ReactJSTraining/history/issues/243.

Do you have a repro?

**Comment by MoOx** [comment]
Not a short one

```console
git clone https://github.com/MoOx/phenomic.git
cd phenomic
git checkout 1e6d472
npm i
npm run docs-start
```

then navigate to any page from the header and click on the logo (which is a  Link to /)

The code that initiate the router is in `src/client/index.js`. Not that this bug happened after we added `useScroll` via `applyRouterMiddleware`.

**Comment by sompylasar** [comment]
@MoOx @taion @craigbeck  

The reduced repro of the aforementioned exception is to visit a URL with two slashes in front of the pathname: `http://www.example.com//` , the culprit is the double slash `//` at the beginning of the URL pathname. The double slash is handled as absolute protocol-relative URL by the browser History API's `replaceState` method which accepts `URL` as the third parameter.

* https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method
* https://github.com/ReactTraining/react-router/issues/3184#issuecomment-196553043

The version `2.0.0` of the [`history` module](https://github.com/reacttraining/history) treats this parameter as `path`, not sanitizing it from extra front slashes which trigger that special absolute URL behavior of History API.

* https://github.com/ReactTraining/history/blob/v2.0.0/modules/createBrowserHistory.js#L92
* https://github.com/ReactTraining/history/blob/b4def645e6ffd99cbee7a387717b826493f07972/modules/createBrowserHistory.js#L92
<img width="715" alt="screen shot 2017-04-11 at 11 41 43 am" src="https://cloud.githubusercontent.com/assets/498274/24926005/fdedb86e-1eae-11e7-8a9d-86d8a3c12459.png">

The bug https://github.com/ReactTraining/history/issues/243 has been first closed with a "warning", but the real fix was introduced later during one of the rewrites of the `history` module.

The latest version `4.6.1`, which has been rewritten at least twice since `2.0.0`, correctly builds the full URL and provides it to the browser History API.

* https://github.com/ReactTraining/history/blob/v4.6.1/modules/createBrowserHistory.js#L212
* https://github.com/ReactTraining/history/blob/a647c5d1e5442998855700195b80a8a60b7f7656/modules/createBrowserHistory.js#L212

That's where updating dependencies can fix bugs.
