### ISSUE TITLE
POP history will clear function in location.state?

### ISSUE THREAD

**Issue by durunvo** [reactjs/react-router#3221]
Hi, im just not sure what is going on, is this expected behaviour or not.

First of, I what to send function around in state of location

`/path1`
    
      const state = {
        action: () => {},
        other: 'other'
      }
      this.props.history.replaceState(state, '/path2')

then i will send the state around to some route
`/path2`
    
      this.props.history.replaceState(this.props.location.state, '/path3')

at this point if i log the state of location, `action` still there

    console.log(this.props.location.state) //  print { action: fn(), other: 'other' }

But when I perform `go back` on the browser, right now i am at route `/path1`

    console.log(this.props.location.state) //  print { other: 'other' }

You guys can see that the `function` is removed from location's state.
My question is why this happening? Is there any reason behind this?

Even if I put `function` into Object
For example
    
      const state = {
        action: { moreAction: () => {} },
        other: 'other'
      }
      this.props.history.replaceState(state, '/path2')

When perform go back in browser, the location's state still be like

    console.log(this.props.location.state) //  print { action: {}, other: 'other' }

Thank you in advance

**Comment by taion** [comment]
Thanks for your question!

We want to make sure that the GitHub issue tracker remains the best place to track bug reports and feature requests that affect the development of React Router, and per the issue template, we are not handling support requests here.

If you have a question or otherwise need help, please post on Stack Overflow with the #react-router tag at https://stackoverflow.com/questions/ask?tags=react-router, or drop in on the #react-router room on Reactiflux at https://discord.gg/0ZcbPKXt5bYaNQ46.
