### ISSUE TITLE
API doc introduction confuse

### ISSUE THREAD

**Issue by caiyongmin** [reactjs/react-router#3224]
## Version

[README](https://github.com/reactjs/react-router#readme)

## Test Case

[Introduction Code](https://github.com/reactjs/react-router/blob/master/docs/Introduction.md)

## Steps to reproduce

I try to make the practice according to the doc code, but when coder the following code, I get a error message.(it's in Adding More UI h2)

```javascript
// Make a new component to render inside of Inbox
const Message = React.createClass({
  render() {
    return <h3>Message</h3>
  }
})

const Inbox = React.createClass({
  render() {
    return (
      <div>
        <h2>Inbox</h2>
        {/* Render the child route component */}
        {this.props.children}
      </div>
    )
  }
})

render((
  <Router history={history}>
    <Route path="/" component={App}>
      <IndexRoute component={Home} />
      <Route path="about" component={About} />
      <Route path="inbox" component={Inbox}>
        {/* add some nested routes where we want the UI to nest */}
        {/* render the stats page when at `/inbox` */}
        <IndexRoute component={InboxStats}/>
        {/* render the message component at /inbox/messages/123 */}
        <Route path="messages/:id" component={Message} />
      </Route>
    </Route>
  </Router>
), document.body)
```

## Error Msg

```bash
Uncaught ReferenceError: InboxStats is not defined
```

## Expected Behavior

no error message, and the application is run well.

## Finally

I'think should declaration the `InboxStats` component. like this:

```javascript
const InboxStats = React.createClass({
  render() {
    return (
      <div>
        some DOM code
      </div>
    )
  }
})
```

thanks!

**Comment by taion** [comment]
Thanks for your question!

We want to make sure that the GitHub issue tracker remains the best place to track bug reports and feature requests that affect the development of React Router, and per the issue template, we are not handling support requests here.

If you have a question or otherwise need help, please post on Stack Overflow with the #react-router tag at https://stackoverflow.com/questions/ask?tags=react-router, or drop in on the #react-router room on Reactiflux at https://discord.gg/0ZcbPKXt5bYaNQ46.

**Comment by caiyongmin** [comment]
Oh, I know! I'm feel sorry about my issue.
