### ISSUE TITLE
Manual navigation to root

### ISSUE THREAD

**Issue by beckend** [reactjs/react-router#3226]
Version 2.0.1

In any flux action handler:
```
const { browserHistory } = require('react-router');
browserHistory.replace({
  pathname: '/'
});

```
All other paths navigated correctly, but to root nothing happens.

**Comment by taion** [comment]
Thanks for your question!

We want to make sure that the GitHub issue tracker remains the best place to track bug reports and feature requests that affect the development of React Router, and per the issue template, we are not handling support requests here.

If you have a question or otherwise need help, please post on Stack Overflow with the #react-router tag at https://stackoverflow.com/questions/ask?tags=react-router, or drop in on the #react-router room on Reactiflux at https://discord.gg/0ZcbPKXt5bYaNQ46.
