### ISSUE TITLE
Have problems with the huge-apps example.

### ISSUE THREAD

**Issue by zhaotoday** [reactjs/react-router#3227]
When I use webpack-dev-server to automatic refresh the page, it doesn't work when I change codes of the component. However,  it works when I change codes of the router config files.

**Comment by taion** [comment]
Thanks for your question!

We want to make sure that the GitHub issue tracker remains the best place to track bug reports and feature requests that affect the development of React Router, and per the issue template, we are not handling support requests here.

If you have a question or otherwise need help, please post on Stack Overflow with the #react-router tag at https://stackoverflow.com/questions/ask?tags=react-router, or drop in on the #react-router room on Reactiflux at https://discord.gg/0ZcbPKXt5bYaNQ46.
