### ISSUE TITLE
Link not recognizing active route in a specific scenario

### ISSUE THREAD

**Issue by illinar** [reactjs/react-router#3230]
This is not necessarily the bug in the code (depends on the way you look at it), but at the very least inconsistency between documented (and naturally expected) behavior and the observed result.

Here is the routes definition:
```
<Route path="/">
  <Route path="entries" component={Index} />
  <Route path="entries/:entryId" component={Entry}>
  ...
```
And the following link `<Link to="/entries">`
The question: should the link be active when the current route is `/entries/1`?

According to documentation:
> The \<Link\> will be active if the current route is either the linked route or any descendant of the linked route.

Of course one may disagree, but natural interpretation is that `/entries` is a descendant of `/entries/1`. However, this link is not getting activated since the matching algorithms looks at the tree path:
```
[0] /
[1] entries/:entryId
```
and does not see a required route parameter. Making the parameter optional would result in a route conflict.

I can understand the reason for the current implementation, but it results in very non-intuitive behavior and is inconvenient.

**Comment by taion** [comment]
This is working as intended. If you wanted what you described, you'd instead do e.g.

```js
<Route path="/">
  <Route path="entries">
    <IndexRoute component={Index} />
    <Route path=":entryId" component={Entry} />
  </Route>
</Route>
```

I've been considering changing this behavior to work as you describe, as it would let us significantly speed up the calculation of route active status by just doing a substring comparison rather than full route matching, but that would be a pretty major breaking change.

For now, I'd recommend setting up routes as I describe above – it also reduces the redundancy in your route definition, which I see as a win.
