### ISSUE TITLE
0.13: react no longer has Object.assign

### ISSUE THREAD

**Issue by wmertens** [reactjs/react-router#3265]
## Version
0.13.5

## Test Case
Upgrade project to React v15

## Steps to reproduce
* build

## Expected Behavior
* builds

## Actual Behavior
* fails because react/lib/Object.assign is missing

Relevant code: https://github.com/reactjs/react-router/blob/0.13.x/modules/createRoutesFromReactChildren.js#L3

Not sure any support is still planned for 0.13 but I thought I'd mention it.

**Comment by ev1stensberg** [comment]
Hi Wout! The currently version that is supported is the master branch version, aka v 2.0.1. Since older versions require old dependencies of, in this case react, you should not change to the newest react version, since you want your current build to be equal to the previous dependencies. Say if you have webpack 1.x something and the newest is 2.0. 

If any drastic change happens while you have the oldest, this doesn't matter. If you have the newest, we would have to maintain every old version accordingly to our newest version, which won't be for much use. If you don't agree, file a PR, and let's see what happens! Who knows :+1:

**Comment by timdorr** [comment]
We're not supporting any 0.x versions anymore.
