### ISSUE TITLE
Support React 15 in 0.13.6

### ISSUE THREAD

**Issue by lencioni** [reactjs/react-router#3281]
For folks who aren't able to upgrade React Router past 0.13.5 at this time, it would be really nice if 0.13.6 existed with support for React 15. Are you open to this?

**Comment by ev1stensberg** [comment]
I've not seen the entire source code from v 0.13.5  besides a quick look, but I know it relies on old internal modules from pre 15, ( [Like this](https://github.com/reactjs/react-router/blob/v0.13.5/modules/components/ActiveHandler.js#L3)). Eventually it will take some effort to get rid of those if it's invoking deep nested Proptypes or generally proptypes with this. Another thing, of which I don't know if old version uses, is 'withContext' , which is removed from React by now. 

Any way or another there's two possibilities, or actually three. 

- 1. PR's 
- 2. Someone from reactjs change this up
- 3. Bump up to a version that has removed these, but with side effects for users.

**Comment by taion** [comment]
FWIW, that got added back with a deprecation warning in 15.0.1 exactly to avoid such breakages.

I can't assert with any certainty without testing, but I don't believe anything in the React 14 compatibility update for the v0.13.x line would be incompatible with React 15, so it's really just bumping up the peer dependency and cutting a release.

**Comment by timdorr** [comment]
We've said before that we're not supporting pre-release versions. That's the price of using something pre-1.0.

That being said, I think the best thing here would be a PR, similar to #2262. I don't think anyone here with  commit access is going to want to drag that branch out of cold storage if they can avoid it.

**Comment by ryanflorence** [comment]
I'd 👍  a PR.

**Comment by mjackson** [comment]
@lencioni If you'd like support for this, please make a PR. Thanks :)

**Comment by taion** [comment]
¯\\\_(ツ)_/¯

I got struck by a fit of curiosity as to whether it would "just work", for values of "just work" meaning `npm test` passes.

I believe https://github.com/taion/react-router/commit/66b20d7e0ec3c9754d1b919d42d50105562cf05e is all it takes, but I have no idea whether this would actually work on a real app, since I have nothing that uses React Router v0.13.x.

It might be a starting point if any of you want to put together a proper PR, but I'm not going to make any assertions as to whether it actually works, and I'm probably not going to do this for the next React release. 😛

**Comment by taion** [comment]
I just realized I still had my branch sitting around. I'm PRing it as https://github.com/reactjs/react-router/pull/3607, if any of you care.

If not, I'm going to delete the branch.
