### ISSUE TITLE
How to pass props to sub component

### ISSUE THREAD

**Issue by BernardZhang** [reactjs/react-router#3304]
I have two usage questions about the react-router;
a. How to pass props to the sub component which is dynamic loaded, example in the huge-app demo:
           
       {sidebar}
   How to pass props to the "sidebar" component?

b. If I want to dynamic load common components in the "Message" component, but don't want to add child routes in "Messages" route,  is there any other way do it?

Thanks & Best  regards

**Comment by taion** [comment]
See https://github.com/reactjs/react-router/blob/master/docs/Troubleshooting.md#passing-additional-values-into-route-components for passing in additional values.

For otherwise configuring components, you have access to all the APIs otherwise available in React. The router makes no prescriptions for how you dynamically load data outside of routing.

**Comment by taion** [comment]
You can use a Router middleware to do this if you want.

One reason we don't spread through the route object is because other middlewares may want you to add extra keys onto the route object (e.g. for configuring Relay queries), and we don't want to stick users with extra props we don't explicitly tell them about – that will e.g. trigger warnings on the newest React release.
