### ISSUE TITLE
huge-app, has any difference in getComponent and component attr ?

### ISSUE THREAD

**Issue by Robin-front** [reactjs/react-router#3343]
what is the difference in example/huge-app

```js
{
  path: 'article',
  getComponent (nextState, cb) {
    require.ensure([], (require) => {
      cb(null, Article)
    })
  },
getChildRoutes (location, cb) {
    require.ensure([], (require) => {
      cb(null, [ require('./detail') ])
    })
  }
}
```
and

```js
{
      path: 'article',
      component: Article,
      childRoutes: [  require('./detail') ]
    }
```

**Comment by mxstbr** [comment]
`require.ensure` is a webpack-specific feature that allows you to code split your applications. It will make `detail` and `Article` their own JS files that are only loaded when the routes of these components are opened, instead of putting everything into one big bundle.

For more information about that see [here](https://medium.com/@ryanflorence/welcome-to-future-of-web-application-delivery-9750b7564d9f#.1wupblr10) and [here](blog.mxstbr.com/2016/01/react-apps-with-pages/)!

**Comment by Robin-front** [comment]
@mxstbr  oh, thx! I am so sorry to waste your time
