### ISSUE TITLE
"Polymorphic" modal popup route

### ISSUE THREAD

**Issue by olalonde** [reactjs/react-router#3499]
Sorry for the confusing title, wasn't sure what to call that.

So I have a component which lists images and when the user clicks an image on the list, there is a modal popover which displays the image in full size with some metadata.

I would like the URL to change when the modal is opened but want to keep the page state behind the modal intact so that closing the modal brings you back to the list where you were. However, if the user does a full refresh or goes directly to that URL, it should display a dedicated page that shows the image + metadata (incidentally it would pretty much be the same component displayed inside the modal except without the modal :)). 

I was wondering if this was possible to achieve with react-router. I couldn't figure out a way to do it that didn't feel hackish.

**Comment by timdorr** [comment]
There are ways to handle this, but not without some serious side effects and bug-prone code. I would either not do it, or just add something to a `getComponent` that returns differently depending on a server or client context. 

The only site I see getting away with this is Facebook, but they don't have a full client-side app and don't use a router (at least not in the sense of this one). Doing it with this library is going to be hacky, which is why I wouldn't recommend it. Sorry to be a naysayer, I just don't want to see you deal with this as a hassle down the line.

**Comment by taion** [comment]
See the "pinterest" example, which demonstrates exactly this.

**Comment by olalonde** [comment]
Oh thanks.
