### ISSUE TITLE
parameterized route and absolute routes in combination supported?

### ISSUE THREAD

**Issue by pke** [reactjs/react-router#3521]
I have component that renders a map with a list of markers depending on `:scope` and potentially a detail defined by `:id`.

``` 
<Route path="/:scope" component={MapComponent}>
  <Route path=":id" component={MapComponent}>
</Route>
``` 

it seems that nesting 2 `MapComponent` like this is allowed by the router and does not lead to the `MapComponent` rendered twice.

Now, the problem is I want to have some additional routes being rendered on top of `MapComponent`, whether or not an `:id` was specified.

So paths like:
`/cities`
`/cities/1`
`/about`

should all be possible and the `MapComponent` should be rendered beneath the `About` component.
Question is: How would the routes have to be nested and are there some kind of default values so that `/about` would fill up the missing route params of `MapComponent` with some defaults like `:scope="cities" && :id=""`

**Comment by timdorr** [comment]
First, absolute routes are going away (#3319).

You've got a subtle misunderstanding of how routes nest. For the `/cities/1` url, what essentially gets rendered is:
```js
<MapComponent>
  <MapComponent />
</MapComponent>
```
or in other words:
```js
<MapComponent children={<MapComponent>}>
```
So, you've got an odd route combination. The MapComponent isn't rendered twice because it's not rendering `this.props.children`. This would be a better config:
```js
<Route path="/:scope">
  <IndexRoute  component={MapComponent} />
  <Route path=":id" component={MapComponent} />
</Route>
```
You only get the `id` param because we pass the fully parse params to every route component. So, it's a happy accident all of this works. But it would be better with a proper `<IndexRoute>`.

**Comment by pke** [comment]
Thanks Tim, I always suspected something looks fishy with the routes. Copied that schema somewhere from the web.
Sad to see absolute routes to go away. I found them quite easy to spot in the config
