### ISSUE TITLE
router listener called multiple times for redirects

### ISSUE THREAD

**Issue by pke** [reactjs/react-router#3525]
I did not find any information about that in the docs.
I am using this listener code in my top-level component.

```es6
class App {
  this.context.router.listen(({ action }) => {
      let backAvailable = this.state.backAvailable
      if (action === "PUSH") {
        ++backAvailable
      } else if (action === "POP") {
        --backAvailable
      }
      this.setState({ backAvailable })
 })
}

<Provider store={store}>
  <Router history={history}>
    <Route path="/" component={App}>
      <IndexRedirect to="/garages/me"/>
      <Redirect from="/garages(/:id)" to="/map/garages(/:id)"/>
      <Redirect from="/retailers(/:id)" to="/map/retailers(/:id)"/>
      <Route path="map/:scope">
        <IndexRoute component={HomeContainer}/>
        <Route path=":id" component={HomeContainer}/>
      </Route>
    </Route>
...
```

However navigating to `/` results in the listener being called multiple times with `action==="POP`.
I'd have expected the listener to be called exactly once with `action==="PUSH"`.

If that is the correct behaviour of the router then how would I implement such back button visibility feature?

**Comment by timdorr** [comment]
You have an `<IndexRedirect>` that goes to another `<Redirect>` (why not just go to the final URL directly?), so it's going to [issue multiple `replace`s](https://github.com/reactjs/react-router/blob/master/modules/Redirect.js#L41). This is entirely expected behavior.

BTW, please only use the issue tracker for bug reporting or feature requests. Support requests don't belong here, as very few people will see this issue. Stack Overflow and Reactiflux are better places to get more eyeballs on your issue.

**Comment by pke** [comment]
Thanks. Posted here, cause I considered it an issue.
