### ISSUE TITLE
Cannot determine route or if route isActive from external script

### ISSUE THREAD

**Issue by Jhawins** [reactjs/react-router#3562]
Currently there is no way to get a route or check if a route is active from outside of a React component.

For example using RefluxJS actions if I needed to do something different based on the current route there is no way to.

I would expect to have a utility or something that I can import and check the current route on?
I'd like to avoid passing a bool based on the `this.context.router.isActive` from every component which accesses the RfluxJS Action. Doing that would mean I have to duplicate code in every single component using said actions...

**Comment by timdorr** [comment]
[Router encapsulates all of the router state](https://github.com/reactjs/react-router/blob/master/modules/Router.js#L77). Getting access to that externally would be dangerous because it would not be provided in sync with React's maintenance of it (`setState` is async). You can access history externally, but router state is something that should remain internal.

**Comment by Jhawins** [comment]
@timdorr I'm not asking for access to the router's state, that wouldn't make any sense.

I assumed there could be a utility exposed for matching against the current URL in the same way as `router.isActive` does. I know I can try to match it on my own but I'd rather use what React-router uses so I know the same matches will always be made.
