### ISSUE TITLE
Add entry point for webpack v2

### ISSUE THREAD

**Issue by mrtnbroder** [reactjs/react-router#3788]
Just like for [Redux](https://github.com/reactjs/redux/pull/1871), let's introduce an entry point for webpack v2.

**Comment by taion** [comment]
It's already there on `next`.

It turns out that this makes a broken config for anybody who's using webpack 2 but hasn't turned off module transpilation: https://github.com/relay-tools/react-router-relay/issues/189, https://github.com/relay-tools/react-router-relay/issues/192.

Given everything else that's going on, I'd rather not deal with the support load that comes from this.
